version: '3.9'

services:
  fastapi:
    build: .
    container_name: fastapi_IMSAPP
    ports:
        - "8000:8000"
    depends_on:
        - db
    env_file:
        - .env
    volumes:
        - .:/app
  db:
    image: postgres:15
    container_name: postgres_nzish_ims
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
